package com.app.enums;

public enum WeekDayAndTime {
	
	SUNDAY_LUNCH,SUNDAY_DINNER,
	MONDAY_LUNCH,MONDAY_DINNER,
	TUESDAY_LUNCH,TUESDAY_DINNER,
	WEDNESDAY_LUNCH,WEDNESDAY_DINNER,
	THURSDAY_LUNCH,THURSDAY_DINNER,
	FRIDAY_LUNCH,FRIDAY_DINNER,
	SATURDAY_LUNCH,SATURDAY_DINNER
}
